"""empty message

Revision ID: c7c4a8585cb1
Revises: 83641711f214
Create Date: 2019-04-08 00:22:10.818967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c4a8585cb1'
down_revision = '83641711f214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_formulas',
    sa.Column('formula_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['formula_id'], ['formula.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter_formulas')
    # ### end Alembic commands ###
